apiVersion: v1
kind: Service
metadata:
  name: cicdtest-svc
  labels:
    app: cicdtest-svc
spec: 
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: cicdtest-pod