steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','gcr.io/kubernates-sample-project-007/cicdtest:v1','.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push','gcr.io/kubernates-sample-project-007/cicdtest:v1']
    - name: 'gcr.io/cloud-builders/gke-deploy:stable'
      args: 
        - run
        - --filename=./manifests/
        - --image=gcr.io/kubernates-sample-project-007/cicdtest:v1
        - --location=us-central1-a
        - --cluster=ntegdevops
timeout: 960s
tags: ['mytag1','mytag2']
images:
- 'gcr.io/kubernates-sample-project-007/cicdtest:v1'